stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/adm-import:1.1.3
      pushRemote: true
      registry: index.docker.io
timeout: 60
